version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: ecommerce-backend
    env_file:
      - ./backend/.env
    volumes:
      - backend_data:/app/data
    networks:
      - ecommerce_net
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce-frontend
    networks:
      - ecommerce_net
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce_net

  nginx:
    image: nginx:latest
    container_name: ecommerce-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - ecommerce_net

volumes:
  backend_data:
  mongo_data:

networks:
  ecommerce_net:
    driver: bridge
