name: Deploy via SSM (Dockerfile Only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run deploy-docker.sh via SSM
        run: |
          INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID_MAIN }}

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Docker deploy without compose and nginx" \
            --parameters '{"commands":["export HOME=/home/ssm-user && sudo -u ssm-user bash /home/ssm-user/scripts/deploy-docker.sh"]}' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          for i in {1..30}; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id "$COMMAND_ID" \
              --details \
              --query "CommandInvocations[].Status" \
              --output text)
            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
              break
            fi
            sleep 5
          done

          OUTPUT=$(aws ssm list-command-invocations \
            --command-id "$COMMAND_ID" \
            --details \
            --query "CommandInvocations[].CommandPlugins[].Output" \
            --output text)

          echo "SSM Command Output: $OUTPUT"

          if [ "$STATUS" != "Success" ]; then
            echo "❌ Deployment failed with status: $STATUS"
            exit 1
          fi

          echo "✅ Docker deployment succeeded"
