name: Deploy via SSM to EC2

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Determine Target EC2 Instance
        id: select-ec2
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" == "dev" ]]; then
            echo "instance_id=${{ secrets.EC2_INSTANCE_ID_DEV }}" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "main" ]]; then
            echo "instance_id=${{ secrets.EC2_INSTANCE_ID_MAIN }}" >> $GITHUB_OUTPUT
          else
            echo "Unknown branch. Exiting." && exit 1
          fi

      - name: Check for Frontend Changes
        id: frontend-changed
        run: |
          git fetch origin ${{ github.event.before }}
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for Backend Changes
        id: backend-changed
        run: |
          git fetch origin ${{ github.event.before }}
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Frontend via SSM
        if: steps.frontend-changed.outputs.changed == 'true'
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Frontend App" \
            --instance-ids ${{ steps.select-ec2.outputs.instance_id }} \
            --parameters commands=["bash ~/scripts/deploy-ecommerce-frontend.sh"] \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy Backend via SSM
        if: steps.backend-changed.outputs.changed == 'true'
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Backend App" \
            --instance-ids ${{ steps.select-ec2.outputs.instance_id }} \
            --parameters commands=["bash ~/scripts/deploy-ecommerce-backend.sh"] \
            --region ${{ secrets.AWS_REGION }}
